In [1]:
import numpy as np

In [26]:
A = np.array([
                [10,2,3],
                [4,5,6],
                [7,8,10.7]
              ])

In [17]:
# A'nın boyutları
A.shape

(3, 3)

In [10]:
# Yeniden boyutlandırma
# A.reshape(3,1)

array([[1],
       [2],
       [3]])

In [12]:
# print(A.reshape(3,1))

[[1]
 [2]
 [3]]


In [18]:
# A'nın transpozesi
print(A.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [30]:
# determinant
det = np.linalg.det(A).astype(float)
# print(f"determinant: {det:.4f}")
# print("determinant: {:.4f}".format(det))
print("determinant: %.4f" % (det))

determinant: 44.4000


## Matris Operasyonları

In [57]:
A = np.array([[1,2.1,3],[4,5,6],[7,8,9]]).astype(float)
print(A)

[[1.  2.1 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [35]:
B = A[1,1].copy()

In [36]:
print(B)

5.0


In [37]:
B = 4

In [38]:
print(A)

[[1.  2.1 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [43]:
# slice işlemleri
C = A[1,1:3] # 1. satır, 1. ve 2. sütun

In [44]:
print(C)

[5. 6.]


In [45]:
C = [4,5]

In [46]:
print(A)

[[1.  2.1 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [48]:
D = A[:,1]
print(D)

[2.1 5.  8. ]


In [50]:
E = A # Copy by reference
print(E)

[[1.  2.1 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [51]:
E[1,1] = 9.7

In [52]:
print( A )

[[1.  2.1 3. ]
 [4.  9.7 6. ]
 [7.  8.  9. ]]


In [ ]:
F = A.copy() # Copy by value

In [58]:
# 1. satır ile 2. satırı değiştir

temp = A[1,:].copy()
A[1,:] = A[2,:].copy()
A[2,:] = temp.copy()


In [59]:
print(A)

[[1.  2.1 3. ]
 [7.  8.  9. ]
 [4.  5.  6. ]]


In [60]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
# daha kolay bir yöntem
X[2,:], X[1,:] = X[1,:].copy(), X[2,:].copy()
print(X)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [65]:
# matris çarpımı    

H = np.array([[1,2],[3,4]])
I = np.array([[5,6],[7,8]])

J = H.dot(I) # ya da J = np.dot(H,I)
K = H * I # element element çarpma
L = H.T


print(J)
print(K)
print(L)

[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
[[1 3]
 [2 4]]


In [89]:
def cramer(A,b,hassasiyet=4.0):
    # A: Katsayı matrisi
    # b: Sabit terim vektörü
    # hassasiyet: Çözümün kaç basamaklı olacağı

    # Önce girdileri kontrol edelim
    # A matrisinin kare olup olmadığını kontrol edelim ve b vektör olmalı
    if len(A.shape) != 2 or A.shape[0] != A.shape[1] or len(b.shape) != 1 or b.shape[0] != A.shape[0]:
        print("Katsayı matrisi kare olmalı ve sabit terim vektörü matrisin boyutlarıyla uyumlu olmalı")
        return None

    #if np.linalg.det(A) < np.power(10,-hassasiyet):
    if np.abs(np.linalg.det(A)) < np.power(10,-hassasiyet):
        print("Determinant sıfır veya sıfıra yakın olduğu için çözüm yok")
        return None

    x = np.zeros(A.shape[0])
    for j in range(A.shape[0]):
        Aj = A.copy()
        Aj[:,j] = b.copy()
        x[j] = np.linalg.det(Aj) / np.linalg.det(A)
    
    return np.round(x,int(hassasiyet))


In [90]:
A = np.array([[1,-2,3,7],[3,4,-3,1],[9,-7,3,1],[2,-5,1,4]]).astype(float)
b = np.array([-2,1,4,10]).astype(float)

x = cramer(A,b)

print(x)

[-0.266  -2.3361 -3.5169  0.5921]


## Gauss Metodu

In [93]:
A = np.array([
        [  1,  2,  3,  7,  3],
        [  4,  5,  6,  8,  4],
        [ -1,  2, -6, -3, -2],
        [  1,  6,  2,  2, -1],
        [  2, -1,  3, -9,  1]
    ]).astype(float)
b = np.array([-2,  3,  1, 7, -2]).astype(float)

In [92]:
print(np.linalg.det(A))

-1856.999999999999


In [94]:
# Genişletilmiş denklem matrisi
Ab = np.column_stack((A,b))
print(Ab)

[[ 1.  2.  3.  7.  3. -2.]
 [ 4.  5.  6.  8.  4.  3.]
 [-1.  2. -6. -3. -2.  1.]
 [ 1.  6.  2.  2. -1.  7.]
 [ 2. -1.  3. -9.  1. -2.]]


In [98]:
satır = Ab.shape[0] # satır sayısı
sutun = Ab.shape[1] # sütun sayısı

for j in np.arange(0, sutun,1 ):
    for i in np.arange(j+1, satır, 1):
        Ab[i,j:] = Ab[i,j:].copy() - Ab[j,j:].copy() * Ab[i,j] / Ab[j,j]
    

In [99]:
print(Ab)

[[  1.           2.           3.           7.           3.
   -2.        ]
 [  0.          -3.          -6.         -20.          -8.
   11.        ]
 [  0.           0.         -11.         -22.66666667  -9.66666667
   13.66666667]
 [  0.           0.           0.         -13.12121212  -6.75757576
   12.48484848]
 [  0.           0.           0.           0.           4.2886836
  -11.52886836]]


In [102]:
from IPython.display import display, Math

def print_matrix(array):
    matrix = ''
    for row in array:
        try:
            for number in row:
                matrix += f'{number:.4f}&'
        except TypeError:
            matrix += f'{row}&'
        matrix = matrix[:-1] + r'\\[12pt]'
    display(Math(r'\begin{bmatrix*}[r]'+matrix+r'\end{bmatrix*}'))

In [103]:
print_matrix(Ab)

<IPython.core.display.Math object>